#ifndef __DATA_H__
#define __DATA_H__

#include <string>
using std::string;

const char *s1 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s2 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s3 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s4 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s5 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s6 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s7 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s8 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s9 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s10 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s11 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s12 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s13 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s14 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s15 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s16 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s17 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s18 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s19 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s20 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s21 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s22 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s23 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s24 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s25 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s26 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s27 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";
const char *s28 = "ATTTTTTTTTTTTCCCCCCCCCCCCCCGATTTTTTTTTTTATATATATATATATAAAAAAAAAAAACCTA";

const char s29[] = {'A','T','C','C','G','G','T','C'};
const char s30[] = {'A','T','C','C','G','G','G','C'};
#endif // __DATA_H__